version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: clipsphere_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: clipsphere_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: clipsphere_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/clipsphere-videos;
      /usr/bin/mc policy set public myminio/clipsphere-videos;
      exit 0;
      "

  app:
    build: .
    container_name: clipsphere_app
    ports:
      - "5001:5001"
    env_file: .env
    depends_on:
      - mongodb
      - redis
      - minio

volumes:
  mongodb_data:
  minio_data:
